### ISSUE TITLE
Hi, something wrong : "ReadFile() system call timed out.”

### ISSUE THREAD

**Issue by liam31012** [klasyc/ScpiNet#5]
I’ m using Tektronix  TBS1102C instrument , the usbtmc driver looks like it's ok
![image](https://github.com/user-attachments/assets/9b20b19e-758d-4de5-995d-e0cbb88233b0)

here is my code 
```
using ScpiNet;

Console.WriteLine("Hello, World!");

List<string> devices = UsbScpiConnection.GetUsbDeviceList();

using (IScpiConnection connection = new UsbScpiConnection(devices[0]))
{
    await connection.Open();

    string id = await connection.GetId();
}
Console.ReadLine();

```
the `devies`  has 1 item , it is the instrument , it works good.
but it went wrong on `string id = await connection.GetId();`,  `ReadFile() system call timed out.`, 
help , plz

**Comment by klasyc** [comment]
Hi, your code looks good. There will be some compatibility issue between the oscilloscope and the library. The timeout error usually appears when the oscilloscope receives malformed data, or when the USB communication is wrongly configured. Please, give me some time, I will re-test the library with TBS1057 or TBS1072 scopes and let you know.

Does your oscilloscope work with TekVISA?

**Comment by liam31012** [comment]
Yas!  it works well with TekVISA
![image](https://github.com/user-attachments/assets/07c5abed-465a-4b5a-bf14-09adbf6bac06)

**Comment by klasyc** [comment]
Hi,

the fault was on my side. My code was configuring the `TransferSize` field in the device request wrongly, when reading the response. Surprisingly, with Keysight multimeter it worked well, but when I connected the Tektronix scope, it did not send any response exactly as in your case.

Anyway, I made a new release 1.1.1 where the bug is fixed. Also, I added a new sample app to the repository and slightly updated the README. Please, let me know if the connection works now.

**Comment by liam31012** [comment]
Ciao
I tested the connection, it works good now, everything is OK, Thanks for your help 👍
